### ISSUE TITLE
Read from CSV file and display on page

### ISSUE THREAD

**Issue by toyboatt** [onepiecememorial/we-remember#28]
Let's get some core functionality in. Read from a CSV file and display it on the page. Doesn't have to look fancy yet, but if we can start showing some names that'd be great.

Here is the link to the existing CSV: https://github.com/onepiecememorial/we-remember/blob/dev/data/lost-nakamas.csv

- add the additional column: country
- the contents of csv should be separated by comma or tab (i.e. name,,country,,year,,text)
- The text should be character limited (lets say 350 for now)

**Comment by Ccastillo06** [comment]
I'll pick the task per our conversation on Discord. Will add more details in the PR.
