### ISSUE TITLE
[PG] Add search feature when in the poneglyph page

### ISSUE THREAD

**Issue by Ccastillo06** [onepiecememorial/we-remember#40]
When navigating the poneglyph page, allow the search bar to filter out specific names from the list.

Can be created with a simple `.filter(str => str.includes(filterText))` after normalizing the text values. An alternativa with fuzzy search could be implemented using Fuse https://fusejs.io/, I'll leave that to be decided by the person implementing this.

**Comment by msolefonte** [comment]
At the moment it looks like it is not necessary. We can go back into it once we get everything else solved.
